---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plepic-assets
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
