---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql.yaml
  - redis.yaml
  - assets-pvc.yaml
  - backend.yaml
  - worker.yaml
  - storefront.yaml
  - service.yaml
  - networkpolicy.yaml
  - predeploy-job.yaml
  - import-job.yaml
  - rbac.yaml
