---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servitium
nameSuffix: ""
resources:
  - ../../base
images:
  - name: ghcr.io/hannosirkel/servitium
    newName: ghcr.io/hannosirkel/servitium
    digest: sha256:ada8ce5aa44d6a5754a88f3ba7462bec4bf3b6e220ad9bd164ed084a85c511f7
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
