---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servitium
nameSuffix: ""
resources:
  - ../../base
images:
  - name: ghcr.io/hannosirkel/servitium
    newName: ghcr.io/hannosirkel/servitium
    digest: sha256:57d4ea713aef1c29a8dd6eaf9f6c26f25e831139861cefa41297a5a86b3aa704
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
