---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servitium
nameSuffix: ""
resources:
  - ../../base
images:
  - name: ghcr.io/hannosirkel/servitium
    newName: ghcr.io/hannosirkel/servitium
    digest: sha256:b5cd7e3fff6a336d18c7b52081714d29c05b273c4265de8d458e62d8f9e4d434
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
