---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servitium
nameSuffix: ""
resources:
  - ../../base
images:
  - name: ghcr.io/hannosirkel/servitium
    newName: ghcr.io/hannosirkel/servitium
    digest: sha256:6cf8e028160e58e8b442541d5a3ef9131c43cd507a60908c785d90ca0a1a2e19
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
