apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-portal
resources:
  - ../../base
images:
  - name: ghcr.io/hannosirkel/ai-portal
    newName: ghcr.io/hannosirkel/ai-portal
    digest: sha256:4ffb1ff8f12290a59b1238eec5d44e40347ea7ade9316b781020052acdaa92f9
