apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-portal
resources:
  - ../../base
images:
  - name: ghcr.io/hannosirkel/ai-portal
    newName: ghcr.io/hannosirkel/ai-portal
    digest: sha256:96c5de94b5048090f995a5a03d02cf350b2b102b9686bf1bb63b8eacf0be479f
